end/Project1/bookdemo/bookdemo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('booktest/', include('booktest.urls')),
    path('', include('booktest.urls', namespace='booktest')),
    path('polls/', include('polls.urls', namespace='polls')),
    path('vote/', include('vote.urls', namespace='vote')),
    path('download/', include('download.urls', namespace='download')),

    #     媒体资源
    # path('<path:path>',serve,{'document_root':MEDIA_POOT})
]

end/Project1/bookdemo/vote/urls.py
from django.conf.urls import url

from . import views

app_name = "vote"
urlpatterns = [
    # 一、视图函数FBV
    # url(r'^$', views.index, name='index'),
    # url(r'^detail/(\d+)/$', views.detail, name='detail'),
    # url(r'^result/(\d+)/$', views.result, name='result'),
    # 二、视图类CBV
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^regist/$', views.regist, name='regist'),
    url(r'^loginout/$', views.loginout, name='loginout'),
    # url(r'^detail/(\d+)/$', views.DetailView.as_view(), name='detail'),
    #
    # url(r'^result/(\d+)/$', views.Result.as_view(), name='result'),

    url(r'^detail/(\d+)/$', views.detail, name='detail'),
    url(r'^result/(\d+)/$', views.result, name='result'),
    url(r'^look/$', views.IndexView.as_view(), name='look'),
]

end/Project1/bookdemo/vote/models.py
from django.db import models
# 使用django自带的用户类
from django.contrib.auth.models import AbstractUser


# Create your models here.

class User(AbstractUser):
    """
    用户类继承原有类

    """

    telephone = models.CharField(max_length=11, verbose_name="手机号")
    # 一个问题可以被多个用户投票  关系字段写在多方
    problems = models.ManyToManyField('Problem')


class Problem(models.Model):
    title = models.CharField(max_length=30)
    source = models.CharField(max_length=10, default="凭空捏造")

    # create_date = models.DateTimeField(auto_now_add=True,related_name='创建时间')
    def __str__(self):
        return self.title

    class Mate:
        verbose_name = "投票表"
        verbose_name_plural = verbose_name
        # order_ing = ["create_date"]


class Option(models.Model):
    option = models.CharField(max_length=10, verbose_name="选项")
    votenums = models.PositiveIntegerField(verbose_name="票数", default=0)
    # create_date = models.DateTimeField(auto_now_add=True,related_name='创建时间')
    problem = models.ForeignKey('Problem', on_delete=models.CASCADE, related_name="problems", verbose_name="所属问题")

    def __str__(self):
        return self.option

    class Mate:
        verbose_name = "选项表"
        verbose_name_plural = verbose_name

        # order_ing = ["create_date"]

end/Project1/bookdemo/vote/views.py
from django.shortcuts import render, redirect, reverse
from django.template import loader
from django.http import HttpResponse

from .models import Problem, Option, User
from .form import LoginForm,RegistForm

from django.views.generic import View, TemplateView, ListView, CreateView, DetailView as DV, DeleteView, UpdateView

from django.contrib.auth import login as lin,authenticate,logout as lout
# View 类是所有视图响应类的基（父）类
# 基于CBV的形式实现

# class IndexView(View):
#     def get(self, request):
#         return HttpResponse("扩展View")


def login(request):
    # return HttpResponse("登录")
    if request.method == "GET":
        # 1.传统 需要自己编写html表单
        # return render(request, 'vote/login.html', )
        # 2. 使用表单类html表单
        lf = LoginForm()
        return render(request, 'vote/login.html',{'lf':lf} )
    elif request.method == "POST":
        lf = LoginForm(request.POST)
        if lf.is_valid():
            username = lf.cleaned_data["username"]
            password = lf.cleaned_data["password"]


            # username = request.POST.get("username")
            # password = request.POST.get("password")
            # 验证登录可以使用django自带的用户认证系统 认证成功返回用户 失败返回 None
            # user = authenticate(username = username,password = password)
            user = User.objects.get(username=username)
            print(user)
            print(user.password)
            # 因为使用表单类用户的密码是未加密状态，不能使用django登录认证系统
            if user.password == password:
            # if user:
                # 认证成功 生成cookie
                lin(request, user)

                # 检验以下 来（登录）之前有没有准备进入详情页
                next_url = request.GET.get("next")
                if next_url:
                    url = next_url
                else:
                    url = reverse("vote:index")
                return redirect(to=url)
            else:
                # url = reverse("vote:login")
                # return redirect(to=url)
                return render(request, "vote/login.html", {'errors': "用户名或密码错误","lf":lf})

        # return HttpResponse("登录")
        else:
            return HttpResponse("出现未知错误，登录失败")


def regist(request):
    if request.method == "GET":
        # return render(request, 'vote/regist.html')
        # 3.使用模型表单类
        rf = RegistForm()
        return render(request,"vote/regist.html",{"rf":rf})

    elif request.method == "POST":
        rf = RegistForm(request.POST)
        if rf.is_valid():
            print(rf, rf.cleaned_data["username"])

            username = rf.cleaned_data["username"]
            password = rf.cleaned_data["password"]
            repassword = rf.cleaned_data["repassword"]

            # 模型表单自带用户查重，无法注册重复用户名，不需要自己检测
            if password !=repassword:
                # return HttpResponse("密码不一致")
                return render(request, "vote/regist.html", {'errors': "密码不一致","rf":rf})

            else:
                # User.objects.create_user(username=username,password=password)
                rf.save()
                url = reverse("vote:login")
                return redirect(to=url)
        else:
            return render(request, "vote/regist.html", {'errors': "用户名已存在或密码不一致", "rf": rf})


    #     username = request.POST.get("username")
    #     password = request.POST.get("password")
    #     repassword = request.POST.get("repassword")
    #     if User.objects.filter(username = username).count() > 0:
    #         # return HttpResponse("用户名已存在")
    #         return render(request,"vote/regist.html",{'errors':"用户名已存在","rf":rf})
    #     else:
    #         if password !=repassword:
    #             # return HttpResponse("密码不一致")
    #             return render(request, "vote/regist.html", {'errors': "密码不一致","rf":rf})
    #
    #         else:
    #             # User.objects.create_user(username=username,password=password)
    #             rf.save()
    #             url = reverse("vote:login")
    #             return redirect(to=url)
    # # return HttpResponse("注册")
    # else:
    #     return HttpResponse("出现未知错误，注册失败")

def loginout(request):
    # 删除 cookie

    lout(request)
    url = reverse("vote:index")

    return redirect(to=url)
    # return HttpResponse("退出")


class IndexView(ListView):
    # 方法二、继承的ListView
    # 指明使用的模板
    template_name = "vote/index.html"
    # 指明返回的结果
    queryset = Problem.objects.all()
    # 指明返回字典的键
    context_object_name = "problems"

    # 方法一、继承的TemplateView
    # template_name = "vote/index.html"
    # def get_context_data(self, **kwargs):
    #     return {"problems":Problem.objects.all()}


# Create your views here.
def index(request):
    problems = Problem.objects.all()
    return render(request, 'vote/index.html', {'problems': problems})


def detail(request, problemid):
    if request.method == 'GET':
        print("当前用户",request.user.username)
        if request.user and request.user.username != "":
            # 已经登录
            print(request.user.problems)
            print(type(request.user.problems))
            try:
                problem = Problem.objects.get(id=problemid)
                # print(problem.option.all)
                if problem in request.user.problems.all():
                    print("已经投过票了")
                    url = reverse("vote:result",args=(problemid))
                    return redirect(to=url)
                else:

                    return render(request, 'vote/detail.html', {'problem': problem})
            except EnvironmentError as e:
                print(e)

                return HttpResponse("问题不合法！")
        else:
            # 登录之后 跳转之前点击过的详情页
            url = reverse("vote:login")+"?next=/vote/detail/"+problemid+"/"
            return redirect(to=url)
    elif request.method == 'POST':
        try:
            print(request.POST.get("option"))
            option_id = request.POST.get("option")
            option = Option.objects.get(id=option_id)
            print(option)
            option.votenums += 1
            option.save()
            # 关联用户和问题
            request.user.problems.add(Problem.objects.get(id=problemid))

            # return HttpResponse("投票成功")
            url = reverse("vote:result", args=(problemid,))
            return redirect(to=url)
        except:

            return HttpResponse("问题不合法！")

        # return render(request, 'polls_votenums.html', {'problem': problem})


#
#
class DetailView(View):
    def get(self, request, problemid):
        try:
            problem = Problem.objects.get(id=problemid)
            # print(problem.option.all)
            return render(request, 'vote/detail.html', {'problem': problem})
        except EnvironmentError as e:
            print(e)

            return HttpResponse("问题不合法！")

    def post(self, request, problemid):
        try:
            print(request.POST.get("option"))
            option_id = request.POST.get("option")
            option = Option.objects.get(id=option_id)
            print(option)
            option.votenums += 1
            option.save()

            # return HttpResponse("投票成功")
            url = reverse("vote:result", args=(problemid,))
            return redirect(to=url)
        except:

            return HttpResponse("问题不合法！")


def result(request, problemid):
    problem = Problem.objects.get(id=problemid)
    return render(request, 'vote/result.html', {'problem': problem})


class Result(View):
    def get(self, request, problemid):
        problem = Problem.objects.get(id=problemid)
        return render(request, 'vote/result.html', {'problem': problem})

end/Project1/bookdemo/templates/vote/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block Title %}
    <title>Title</title>
    {% endblock %}
    <link rel="stylesheet" href="/static/css/main.css">
</head>

<body>
<div class="container">
    {% block header %}
    {# 这里是头部 #}
    <div class="">
        {% if request.user and request.user.username != ''%}
        当前用户：{{request.user}}
        <button><a href="{% url 'vote:loginout' %}">退出</a></button>

        {% else %}
        <button><a href="{% url 'vote:login' %}">登录</a></button>
        <button><a href="{% url 'vote:regist' %}">注册</a></button>
        {% endif %}


    </div>
    {% endblock %}

    {% block body %}
    <br>
    这里是身体
    {% endblock %}

    {% block footer %}
    <br>
    {# 这里是底部 #}
    <button><a href="{% url 'booktest:index' %}">返回主页面</a></button>
    {% endblock %}
</div>
</body>
</html>

end/Project1/bookdemo/templates/vote/detail.html
{% extends 'vote/base.html' %}
{% block Title %}
    <title>投票详情</title>

{% endblock %}
{% block body %}
     <h1>投票问题：{{problem}}</h1>
    <h2>选项:</h2>
    <form action="#" method="post">
        {# 阻止跨站请求 #}
        {% csrf_token %}
        {% for option in problem.problems.all %}
        {% if forloop.counter == 1 %}
        <input type="radio" name="option" value="{{option.id}}" checked>{{option}}
        {% else %}
        <input type="radio" name="option" value="{{option.id}}">{{option}}
        {% endif %}
        {% endfor %}
        <input type="submit" value="投票">
        <button><a href="{% url 'vote:index' %}">返回</a></button>

    </form>

{% endblock %}

end/Project1/bookdemo/templates/vote/index.html
{% extends 'vote/base.html' %}
{% block Title %}
<title>投票首页</title>

{% endblock %}
{% block body %}
<h3>首页</h3>

{% for problem in problems %}
<a href="{% url 'vote:detail' problem.id %}">{{forloop.counter}}.{{problem }}</a>
<br>

{% endfor %}


{% endblock %}

end/Project1/bookdemo/templates/vote/login.html
{% extends 'vote/base.html' %}
{% block Title %}
<title>登录</title>

{% endblock %}
{% block body %}
{% comment %}
<br>
<form action="#" method="post">
    {% csrf_token %}
    用户名：<input type="text" name="username" required>
    <br>
    密码：<input type="password" name="password" required>
    <br>

    <input type="submit" value="登录">
    {{username}}
    {% if username %}
    666

    {% endif %}
    {{errors}}

</form>
{% endcomment %}

<form action="#" method="post">
    {% csrf_token %}
    {# {{lf}} #}
    {{lf.username.label}}:{{lf.username}}
    <br>
    {{lf.username.help_text}}
    <br>
    {{lf.password.label}}:{{lf.password}}
    <br>
    {{lf.password.help_text}}
    <br>
    <input type="submit" value="登录">
    {{errors}}
</form>
{% endblock %}

end/Project1/bookdemo/templates/vote/regist.html
{% extends 'vote/base.html' %}
{% block Title %}
<title>注册</title>

{% endblock %}
{% block body %}
<br>
<form action="#" method="post">
    {% csrf_token %}
    {% comment %}
    用户名：<input type="text" name="username" required>
    <br>
    密码：<input type="password" name="password" required>
    <br>
    重复密码：<input type="password" name="repassword" required>
    <br>
    {% endcomment %}
    {{rf.username.label}}:{{rf.username}}
    <br>

    {{rf.password.label}}:{{rf.password}}
    <br>
    {{rf.repassword.label}}:{{rf.repassword}}

    <br>
    <input type="submit" value="注册">


    <p>{{errors}}</p>
</form>
{% endblock %}

end/Project1/bookdemo/templates/vote/result.html
{% extends 'vote/base.html' %}
{% block Title %}
    <title>票数</title>

{% endblock %}
{% block body %}
    <h3>具体票数</h3>
    {% for option in problem.problems.all %}
    {{option}}:{{option.votenums}}
    <br>
    {% endfor %}
        <button><a href="{% url 'vote:index' %}">返回</a></button>


{% endblock %}